import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { BigHero } from '../src/components/BigHero'
import { Header } from '../src/components/Header'
import { Hero } from '../src/components/Hero'

const Home: NextPage = () => {
  return (
    <div>
      <Header/>
      <Hero/>
      <BigHero/>
      
      <Head>
        <title>Movie App Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     
    </div>
  )
}

export default Home
